import { FastifyInstance } from 'fastify'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'

const SEED_ACCOUNTS = [
  // ── 資產 (1xxx) ──────────────────────────────────────────
  { code: '1',      name: '資產總額',                         category: 'ASSET' },
  { code: '11',     name: '流動資產',                         category: 'ASSET' },
  { code: '1111',   name: '現金',                             category: 'ASSET' },
  { code: '1112',   name: '銀行存款',                         category: 'ASSET' },
  { code: '111201', name: '銀行存款-中信#2017',               category: 'ASSET' },
  { code: '111202', name: '銀行存款-陽信#5677',               category: 'ASSET' },
  { code: '1113',   name: '約當現金',                         category: 'ASSET' },
  { code: '1114',   name: '短期性之投資',                     category: 'ASSET' },
  { code: '1121',   name: '應收票據',                         category: 'ASSET' },
  { code: '1122',   name: '應收票據-備抵呆帳',               category: 'ASSET' },
  { code: '1123',   name: '應收帳款',                         category: 'ASSET' },
  { code: '1124',   name: '應收帳款-備抵呆帳',               category: 'ASSET' },
  { code: '1125',   name: '合約資產-流動',                   category: 'ASSET' },
  { code: '1126',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '1129',   name: '其他應收款',                       category: 'ASSET' },
  { code: '113',    name: '存貨',                             category: 'ASSET' },
  { code: '1131',   name: '商品存貨',                         category: 'ASSET' },
  { code: '1132',   name: '製成品存貨',                       category: 'ASSET' },
  { code: '1133',   name: '在製品(在建工程)存貨',             category: 'ASSET' },
  { code: '1134',   name: '原料存貨',                         category: 'ASSET' },
  { code: '1135',   name: '物料存貨',                         category: 'ASSET' },
  { code: '1136',   name: '寄銷品存貨',                       category: 'ASSET' },
  { code: '1137',   name: '減:備抵存貨跌價',                 category: 'ASSET' },
  { code: '1138',   name: '存貨-其他',                        category: 'ASSET' },
  { code: '114',    name: '預付款項',                         category: 'ASSET' },
  { code: '1141',   name: '預付費用',                         category: 'ASSET' },
  { code: '1142',   name: '用品盤存',                         category: 'ASSET' },
  { code: '1143',   name: '預付貨款',                         category: 'ASSET' },
  { code: '1144',   name: '進項稅額',                         category: 'ASSET' },
  { code: '1145',   name: '留抵稅額',                         category: 'ASSET' },
  { code: '1149',   name: '其他預付款',                       category: 'ASSET' },
  { code: '1151',   name: '公允價值之金融資產',               category: 'ASSET' },
  { code: '1154',   name: '避險之金融資產',                   category: 'ASSET' },
  { code: '1157',   name: '其他金融資產',                     category: 'ASSET' },
  { code: '1158',   name: '其他綜合損益公允價值',             category: 'ASSET' },
  { code: '1159',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '1161',   name: '按攤銷後成本衡量資產',             category: 'ASSET' },
  { code: '119',    name: '其他流動資產',                     category: 'ASSET' },
  { code: '1191',   name: '暫付款',                           category: 'ASSET' },
  { code: '1192',   name: '股東往來',                         category: 'ASSET' },
  { code: '1193',   name: '同業往來',                         category: 'ASSET' },
  { code: '1199',   name: '其他流動資產-其他',               category: 'ASSET' },
  { code: '119901', name: '應退稅額',                         category: 'ASSET' },
  { code: '119902', name: '其他',                             category: 'ASSET' },
  { code: '12',     name: '非流動資產',                       category: 'ASSET' },
  { code: '1300',   name: '長期性之投資',                     category: 'ASSET' },
  { code: '13001',  name: '以成本衡量之金融資產',             category: 'ASSET' },
  { code: '1302',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '14',     name: '固定資產',                         category: 'ASSET' },
  { code: '1410',   name: '土地',                             category: 'ASSET' },
  { code: '1411',   name: '累計減損-土地',                   category: 'ASSET' },
  { code: '1421',   name: '礦產資源',                         category: 'ASSET' },
  { code: '1422',   name: '累計折耗-礦產資源',               category: 'ASSET' },
  { code: '1423',   name: '累計減損-礦產資源',               category: 'ASSET' },
  { code: '1431',   name: '房屋及建築',                       category: 'ASSET' },
  { code: '1432',   name: '累計折舊-房屋及建築',             category: 'ASSET' },
  { code: '1433',   name: '累計減損-房屋及建築',             category: 'ASSET' },
  { code: '1441',   name: '機器設備',                         category: 'ASSET' },
  { code: '1442',   name: '累計折舊-機器設備',               category: 'ASSET' },
  { code: '1443',   name: '累計減損-機器設備',               category: 'ASSET' },
  { code: '1451',   name: '運輸設備',                         category: 'ASSET' },
  { code: '1452',   name: '累計折舊-運輸設備',               category: 'ASSET' },
  { code: '1453',   name: '累計減損-運輸設備',               category: 'ASSET' },
  { code: '1461',   name: '辦公設備',                         category: 'ASSET' },
  { code: '1462',   name: '累計折舊-辦公設備',               category: 'ASSET' },
  { code: '1463',   name: '累計減損-辦公設備',               category: 'ASSET' },
  { code: '1470',   name: '未完工程及待驗設備',               category: 'ASSET' },
  { code: '1491',   name: '其他固定資產',                     category: 'ASSET' },
  { code: '1492',   name: '其他固定資產累計折舊',             category: 'ASSET' },
  { code: '1493',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '1510',   name: '無形資產',                         category: 'ASSET' },
  { code: '1511',   name: '無形資產-累計攤折',               category: 'ASSET' },
  { code: '1512',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '1541',   name: '投資性不動產',                     category: 'ASSET' },
  { code: '1542',   name: '累計折舊投資性不動產',             category: 'ASSET' },
  { code: '1543',   name: '累計減損投資性不動產',             category: 'ASSET' },
  { code: '1551',   name: '生物資產',                         category: 'ASSET' },
  { code: '1552',   name: '累計折舊-生物資產',               category: 'ASSET' },
  { code: '1553',   name: '累計減損-生物資產',               category: 'ASSET' },
  { code: '1612',   name: '公允價值之金融資產',               category: 'ASSET' },
  { code: '1615',   name: '避險之金融資產',                   category: 'ASSET' },
  { code: '1618',   name: '其他金融資產',                     category: 'ASSET' },
  { code: '1621',   name: '其他綜合損益公允價值',             category: 'ASSET' },
  { code: '1622',   name: '按攤銷後成本衡量資產',             category: 'ASSET' },
  { code: '1630',   name: '採用權益法之投資',                 category: 'ASSET' },
  { code: '1631',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '1640',   name: '合約資產-非流動',                 category: 'ASSET' },
  { code: '1641',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '1710',   name: '使用權資產',                       category: 'ASSET' },
  { code: '1711',   name: '減:累計折舊',                     category: 'ASSET' },
  { code: '1712',   name: '減:累計減損',                     category: 'ASSET' },
  { code: '19',     name: '其他非流動資產',                   category: 'ASSET' },
  { code: '1901',   name: '存出保證金',                       category: 'ASSET' },
  { code: '1902',   name: '未攤銷費用',                       category: 'ASSET' },
  { code: '1903',   name: '預付設備款',                       category: 'ASSET' },
  { code: '1904',   name: '其他非流動資產-其他',             category: 'ASSET' },
  // ── 負債 (2xxx) ──────────────────────────────────────────
  { code: '2',      name: '負債總額',                         category: 'LIABILITY' },
  { code: '21',     name: '流動負債',                         category: 'LIABILITY' },
  { code: '211',    name: '短期借款',                         category: 'LIABILITY' },
  { code: '2111',   name: '銀行透支',                         category: 'LIABILITY' },
  { code: '2112',   name: '銀行借款',                         category: 'LIABILITY' },
  { code: '2113',   name: '應付短期票券',                     category: 'LIABILITY' },
  { code: '2119',   name: '其他短期借款',                     category: 'LIABILITY' },
  { code: '2120',   name: '應付票據',                         category: 'LIABILITY' },
  { code: '2121',   name: '應付帳款',                         category: 'LIABILITY' },
  { code: '2126',   name: '合約負債-流動',                   category: 'LIABILITY' },
  { code: '213',    name: '其他應付款',                       category: 'LIABILITY' },
  { code: '2131',   name: '應付費用',                         category: 'LIABILITY' },
  { code: '2132',   name: '應付稅捐',                         category: 'LIABILITY' },
  { code: '2133',   name: '應付股利',                         category: 'LIABILITY' },
  { code: '2134',   name: '銷項稅額',                         category: 'LIABILITY' },
  { code: '2135',   name: '其他應付款-其他',                 category: 'LIABILITY' },
  { code: '2136',   name: '預收款項',                         category: 'LIABILITY' },
  { code: '2137',   name: '預收貨款',                         category: 'LIABILITY' },
  { code: '2138',   name: '其他預收款',                       category: 'LIABILITY' },
  { code: '2140',   name: '公允價值之金融負債',               category: 'LIABILITY' },
  { code: '2150',   name: '避險之金融負債',                   category: 'LIABILITY' },
  { code: '2170',   name: '特別股負債',                       category: 'LIABILITY' },
  { code: '2180',   name: '其他金融負債',                     category: 'LIABILITY' },
  { code: '219',    name: '其他流動負債',                     category: 'LIABILITY' },
  { code: '2191',   name: '暫收款',                           category: 'LIABILITY' },
  { code: '2192',   name: '股東往來',                         category: 'LIABILITY' },
  { code: '2193',   name: '同業往來',                         category: 'LIABILITY' },
  { code: '2195',   name: '代收款',                           category: 'LIABILITY' },
  { code: '2196',   name: '其他流動負債-其他',               category: 'LIABILITY' },
  { code: '22',     name: '非流動負債',                       category: 'LIABILITY' },
  { code: '2210',   name: '應付公司債',                       category: 'LIABILITY' },
  { code: '2220',   name: '長期借款',                         category: 'LIABILITY' },
  { code: '2230',   name: '公允價值之金融負債',               category: 'LIABILITY' },
  { code: '2240',   name: '避險之金融負債',                   category: 'LIABILITY' },
  { code: '2260',   name: '特別股負債',                       category: 'LIABILITY' },
  { code: '2270',   name: '其他金融負債',                     category: 'LIABILITY' },
  { code: '2280',   name: '長期應付票據及款項',               category: 'LIABILITY' },
  { code: '2281',   name: '合約負債-非流動',                 category: 'LIABILITY' },
  { code: '2282',   name: '租賃負債',                         category: 'LIABILITY' },
  { code: '2290',   name: '其他長期負債',                     category: 'LIABILITY' },
  { code: '29',     name: '其他非流動負債',                   category: 'LIABILITY' },
  { code: '2910',   name: '存入保證金',                       category: 'LIABILITY' },
  { code: '2940',   name: '退休金準備',                       category: 'LIABILITY' },
  { code: '2951',   name: '國外投資損失準備',                 category: 'LIABILITY' },
  { code: '2970',   name: '受託承銷品',                       category: 'LIABILITY' },
  { code: '2999',   name: '其他非流動負債-其他',             category: 'LIABILITY' },
  // ── 權益 (3xxx) ──────────────────────────────────────────
  { code: '3',      name: '權益總額',                         category: 'EQUITY' },
  { code: '31',     name: '資本或股本(實收)',                 category: 'EQUITY' },
  { code: '3110',   name: '資本(登記)',                       category: 'EQUITY' },
  { code: '3120',   name: '股本-未發行股本',                 category: 'EQUITY' },
  { code: '3130',   name: '股本-預收股款',                   category: 'EQUITY' },
  { code: '3300',   name: '資本公積',                         category: 'EQUITY' },
  { code: '34',     name: '保留盈餘',                         category: 'EQUITY' },
  { code: '341',    name: '法定公積',                         category: 'EQUITY' },
  { code: '3411',   name: '法定公積(86年度以前)',             category: 'EQUITY' },
  { code: '3412',   name: '法定公積(87年度以後)',             category: 'EQUITY' },
  { code: '342',    name: '特別公積',                         category: 'EQUITY' },
  { code: '3421',   name: '特別公積(86年度以前)',             category: 'EQUITY' },
  { code: '3422',   name: '特別公積(87年度以後)',             category: 'EQUITY' },
  { code: '343',    name: '累積盈虧',                         category: 'EQUITY' },
  { code: '3431',   name: '累積盈虧(86年度以前)',             category: 'EQUITY' },
  { code: '3432',   name: '累積盈虧(87年度以後)',             category: 'EQUITY' },
  { code: '3434',   name: '追溯重編之影響數',                 category: 'EQUITY' },
  { code: '3435',   name: '其他權益轉入稅後淨額',             category: 'EQUITY' },
  { code: '3440',   name: '本期損益(稅後)',                   category: 'EQUITY' },
  { code: '3450',   name: '本期盈餘分配撥補虧損',             category: 'EQUITY' },
  { code: '35',     name: '公積及盈餘-其他權益',             category: 'EQUITY' },
  { code: '3502',   name: '避險工具之損益',                   category: 'EQUITY' },
  { code: '3503',   name: '國外財報換算兌換差額',             category: 'EQUITY' },
  { code: '3504',   name: '未實現重估增值',                   category: 'EQUITY' },
  { code: '3505',   name: '確定福利計畫再衡量數',             category: 'EQUITY' },
  { code: '3506',   name: '其他權益-其他',                   category: 'EQUITY' },
  { code: '3507',   name: '按公允衡量未實現損益',             category: 'EQUITY' },
  { code: '3508',   name: '員工未賺得酬勞',                   category: 'EQUITY' },
  { code: '3600',   name: '減:庫藏股票',                     category: 'EQUITY' },
  // ── 營業收入 (4xxx) ──────────────────────────────────────
  { code: '4',      name: '營業收入淨額',                     category: 'REVENUE' },
  { code: '41',     name: '營業收入總額',                     category: 'REVENUE' },
  { code: '4101',   name: '營業收入',                         category: 'REVENUE' },
  { code: '4102',   name: '外匯收入',                         category: 'REVENUE' },
  { code: '410201', name: '三角貿易收入',                     category: 'REVENUE' },
  { code: '4201',   name: '銷貨退回',                         category: 'REVENUE' },
  { code: '4202',   name: '銷貨折讓',                         category: 'REVENUE' },
  // ── 營業成本 (5xxx) ──────────────────────────────────────
  { code: '5',      name: '營業成本',                         category: 'COGS' },
  { code: '50',     name: '進銷成本',                         category: 'COGS' },
  { code: '5010',   name: '期初存貨',                         category: 'COGS' },
  { code: '502',    name: '本期進貨(淨額)',                   category: 'COGS' },
  { code: '5021',   name: '進貨',                             category: 'COGS' },
  { code: '5022',   name: '進貨退出',                         category: 'COGS' },
  { code: '5023',   name: '進貨折讓',                         category: 'COGS' },
  { code: '5030',   name: '期末存貨',                         category: 'COGS' },
  { code: '5040',   name: '進貨-其他(加項)',                 category: 'COGS' },
  { code: '5050',   name: '進貨-其他(減項)',                 category: 'COGS' },
  { code: '51',     name: '直接原料',                         category: 'COGS' },
  { code: '5110',   name: '期初存料-原料',                   category: 'COGS' },
  { code: '512',    name: '本期進料-原料(淨額)',             category: 'COGS' },
  { code: '5121',   name: '原料',                             category: 'COGS' },
  { code: '5122',   name: '原料退出',                         category: 'COGS' },
  { code: '5123',   name: '原料折讓',                         category: 'COGS' },
  { code: '5130',   name: '期末存貨-原料',                   category: 'COGS' },
  { code: '5140',   name: '直接原料-其他(加項)',             category: 'COGS' },
  { code: '5150',   name: '直接原料-其他(減項)',             category: 'COGS' },
  { code: '52',     name: '間接材料',                         category: 'COGS' },
  { code: '5210',   name: '期初存料-物料',                   category: 'COGS' },
  { code: '522',    name: '本期進料-物料(淨額)',             category: 'COGS' },
  { code: '5221',   name: '物料',                             category: 'COGS' },
  { code: '5222',   name: '物料退出',                         category: 'COGS' },
  { code: '5223',   name: '物料折讓',                         category: 'COGS' },
  { code: '5230',   name: '期末存貨-物料',                   category: 'COGS' },
  { code: '5240',   name: '間接材料-其他(加項)',             category: 'COGS' },
  { code: '5250',   name: '間接材料-其他(減項)',             category: 'COGS' },
  { code: '5300',   name: '直接人工',                         category: 'COGS' },
  { code: '54',     name: '製造費用',                         category: 'COGS' },
  { code: '5401',   name: '間接人工-(製)',                   category: 'COGS' },
  { code: '5402',   name: '租金支出-(製)',                   category: 'COGS' },
  { code: '5403',   name: '文具用品-(製)',                   category: 'COGS' },
  { code: '5404',   name: '旅費-(製)',                        category: 'COGS' },
  { code: '5405',   name: '運費-(製)',                        category: 'COGS' },
  { code: '5406',   name: '郵電費-(製)',                      category: 'COGS' },
  { code: '5407',   name: '修繕費-(製)',                      category: 'COGS' },
  { code: '5408',   name: '包裝費-(製)',                      category: 'COGS' },
  { code: '5409',   name: '水電瓦斯費-(製)',                  category: 'COGS' },
  { code: '5410',   name: '保險費-(製)',                      category: 'COGS' },
  { code: '5411',   name: '加工費-(製)',                      category: 'COGS' },
  { code: '5412',   name: '稅捐-(製)',                        category: 'COGS' },
  { code: '5413',   name: '折舊-(製)',                        category: 'COGS' },
  { code: '5414',   name: '各項耗竭及攤提-(製)',              category: 'COGS' },
  { code: '5415',   name: '伙食費-(製)',                      category: 'COGS' },
  { code: '5416',   name: '職工福利-(製)',                    category: 'COGS' },
  { code: '5490',   name: '其他製造費用',                     category: 'COGS' },
  { code: '549001', name: '其他製造費用-1',                   category: 'COGS' },
  { code: '549002', name: '其他製造費用-2',                   category: 'COGS' },
  { code: '5498',   name: '其他製造費用剔除數',               category: 'COGS' },
  { code: '5550',   name: '製造成本',                         category: 'COGS' },
  { code: '5551',   name: '期初在製品盤存',                   category: 'COGS' },
  { code: '5552',   name: '期末在製品盤存',                   category: 'COGS' },
  { code: '5553',   name: '在製品-其他(加項)',               category: 'COGS' },
  { code: '5554',   name: '在製品-其他(減項)',               category: 'COGS' },
  { code: '5560',   name: '製成品成本',                       category: 'COGS' },
  { code: '5561',   name: '期初製成品盤存',                   category: 'COGS' },
  { code: '5562',   name: '期末製成品盤存',                   category: 'COGS' },
  { code: '5563',   name: '製成品-其他(加項)',               category: 'COGS' },
  { code: '5564',   name: '製成品-其他(減項)',               category: 'COGS' },
  { code: '5565',   name: '外銷退稅款',                       category: 'COGS' },
  { code: '5566',   name: '產銷成本減項',                     category: 'COGS' },
  { code: '5570',   name: '產銷成本',                         category: 'COGS' },
  { code: '5600',   name: '勞務成本',                         category: 'COGS' },
  { code: '5700',   name: '修理成本',                         category: 'COGS' },
  { code: '5800',   name: '加工成本',                         category: 'COGS' },
  { code: '5810',   name: '業務成本',                         category: 'COGS' },
  { code: '5900',   name: '其他營業成本',                     category: 'COGS' },
  // ── 營業費用 (6xxx) ──────────────────────────────────────
  { code: '6',      name: '營業費用及損失總額',               category: 'EXPENSE' },
  { code: '6110',   name: '薪資支出',                         category: 'EXPENSE' },
  { code: '6111',   name: '租金支出',                         category: 'EXPENSE' },
  { code: '6112',   name: '文具用品',                         category: 'EXPENSE' },
  { code: '6113',   name: '旅費',                             category: 'EXPENSE' },
  { code: '6114',   name: '運費',                             category: 'EXPENSE' },
  { code: '6115',   name: '郵電費',                           category: 'EXPENSE' },
  { code: '6116',   name: '修繕費',                           category: 'EXPENSE' },
  { code: '6117',   name: '廣告費',                           category: 'EXPENSE' },
  { code: '6118',   name: '水電瓦斯費',                       category: 'EXPENSE' },
  { code: '6119',   name: '保險費',                           category: 'EXPENSE' },
  { code: '6120',   name: '交際費',                           category: 'EXPENSE' },
  { code: '6121',   name: '捐贈',                             category: 'EXPENSE' },
  { code: '6122',   name: '稅捐',                             category: 'EXPENSE' },
  { code: '6123',   name: '呆帳損失',                         category: 'EXPENSE' },
  { code: '6124',   name: '折舊',                             category: 'EXPENSE' },
  { code: '6125',   name: '各項耗竭及攤提',                   category: 'EXPENSE' },
  { code: '6126',   name: '外銷損失',                         category: 'EXPENSE' },
  { code: '6127',   name: '伙食費',                           category: 'EXPENSE' },
  { code: '6128',   name: '職工福利',                         category: 'EXPENSE' },
  { code: '6129',   name: '研究費',                           category: 'EXPENSE' },
  { code: '612901', name: '耗材費用',                         category: 'EXPENSE' },
  { code: '612902', name: '薪資費用',                         category: 'EXPENSE' },
  { code: '612903', name: '租金支出',                         category: 'EXPENSE' },
  { code: '612904', name: '文具用品',                         category: 'EXPENSE' },
  { code: '612905', name: '旅費',                             category: 'EXPENSE' },
  { code: '612906', name: '運費',                             category: 'EXPENSE' },
  { code: '612907', name: '郵電費',                           category: 'EXPENSE' },
  { code: '612908', name: '修繕費',                           category: 'EXPENSE' },
  { code: '612909', name: '水電瓦斯費',                       category: 'EXPENSE' },
  { code: '612910', name: '保險費',                           category: 'EXPENSE' },
  { code: '612911', name: '交際費',                           category: 'EXPENSE' },
  { code: '612912', name: '稅捐',                             category: 'EXPENSE' },
  { code: '612913', name: '折舊',                             category: 'EXPENSE' },
  { code: '612914', name: '各項耗竭及攤提',                   category: 'EXPENSE' },
  { code: '612915', name: '伙食費',                           category: 'EXPENSE' },
  { code: '612916', name: '職工福利',                         category: 'EXPENSE' },
  { code: '612917', name: '權利金',                           category: 'EXPENSE' },
  { code: '612918', name: '勞務費',                           category: 'EXPENSE' },
  { code: '612919', name: '訓練費',                           category: 'EXPENSE' },
  { code: '612920', name: '其他研究發展費用',                 category: 'EXPENSE' },
  { code: '6130',   name: '佣金支出',                         category: 'EXPENSE' },
  { code: '6131',   name: '訓練費',                           category: 'EXPENSE' },
  { code: '6132',   name: '其他費用',                         category: 'EXPENSE' },
  { code: '613201', name: '什費',                             category: 'EXPENSE' },
  { code: '613202', name: '管理費用',                         category: 'EXPENSE' },
  { code: '613203', name: '什項購置',                         category: 'EXPENSE' },
  { code: '613204', name: '書報雜誌',                         category: 'EXPENSE' },
  { code: '613205', name: '文具印刷費',                       category: 'EXPENSE' },
  { code: '613206', name: '燃料費',                           category: 'EXPENSE' },
  { code: '613207', name: '勞工退休金',                       category: 'EXPENSE' },
  { code: '613208', name: '勞務費',                           category: 'EXPENSE' },
  { code: '613209', name: '加班費',                           category: 'EXPENSE' },
  { code: '613210', name: '教育訓練費用',                     category: 'EXPENSE' },
  { code: '613211', name: '包裝費用',                         category: 'EXPENSE' },
  { code: '613212', name: '交通費用',                         category: 'EXPENSE' },
  { code: '6133',   name: '商譽攤銷',                         category: 'EXPENSE' },
  // ── 非營業收入 (7xxx) ────────────────────────────────────
  { code: '7',      name: '非營業收入總額',                   category: 'REVENUE' },
  { code: '7035',   name: '一般股息與紅利',                   category: 'REVENUE' },
  { code: '7036',   name: '特殊股利',                         category: 'REVENUE' },
  { code: '7038',   name: '利息收入',                         category: 'REVENUE' },
  { code: '7039',   name: '租賃收入',                         category: 'REVENUE' },
  { code: '7040',   name: '出售資產盈餘',                     category: 'REVENUE' },
  { code: '7041',   name: '佣金收入',                         category: 'REVENUE' },
  { code: '7042',   name: '商品盤盈',                         category: 'REVENUE' },
  { code: '7043',   name: '兌換盈益',                         category: 'REVENUE' },
  { code: '7044',   name: '其他收入',                         category: 'REVENUE' },
  { code: '7097',   name: '退稅收入',                         category: 'REVENUE' },
  { code: '7098',   name: '國外投資收益',                     category: 'REVENUE' },
  // ── 非營業損失 (8xxx) ────────────────────────────────────
  { code: '8',      name: '非營業損失及費用總額',             category: 'EXPENSE' },
  { code: '8046',   name: '利息支出',                         category: 'EXPENSE' },
  { code: '8047',   name: '投資損失',                         category: 'EXPENSE' },
  { code: '8048',   name: '出售資產損失',                     category: 'EXPENSE' },
  { code: '8049',   name: '災害損失',                         category: 'EXPENSE' },
  { code: '8050',   name: '商品盤損',                         category: 'EXPENSE' },
  { code: '8051',   name: '兌換虧損',                         category: 'EXPENSE' },
  { code: '8052',   name: '其它損失',                         category: 'EXPENSE' },
  // ── 所得稅 (9xxx) ────────────────────────────────────────
  { code: '9999',   name: '所得稅費用',                       category: 'EXPENSE' },
] as const

export default async function accountRoutes(app: FastifyInstance) {
  const auth = { preHandler: [app.authenticate] }

  app.get('/accounts', auth, async (req) => {
    const { category } = req.query as any
    return prisma.chartOfAccount.findMany({
      where: { companyId: req.companyId, isActive: true, ...(category ? { category } : {}) },
      orderBy: { code: 'asc' },
    })
  })

  // 匯入重泰科目表（已存在則略過，新增不足的科目）
  app.post('/accounts/seed', auth, async (req) => {
    const result = await prisma.chartOfAccount.createMany({
      data: SEED_ACCOUNTS.map(a => ({ ...a, companyId: req.companyId })),
      skipDuplicates: true,
    })
    return { message: `已新增 ${result.count} 個科目（共 ${SEED_ACCOUNTS.length} 筆，略過重複）` }
  })

  app.post('/accounts', auth, async (req, reply) => {
    const body = z.object({
      code: z.string(),
      name: z.string(),
      category: z.enum(['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'COGS', 'EXPENSE']),
      parentCode: z.string().optional(),
    }).parse(req.body)
    const account = await prisma.chartOfAccount.create({ data: { ...body, companyId: req.companyId } })
    return reply.code(201).send(account)
  })

  app.patch('/accounts/:id', auth, async (req, reply) => {
    const { id } = req.params as any
    const body = z.object({
      name: z.string().optional(),
      isActive: z.boolean().optional(),
    }).parse(req.body)
    const existing = await prisma.chartOfAccount.findFirst({ where: { id, companyId: req.companyId } })
    if (!existing) return reply.code(404).send({ message: '找不到科目' })
    return prisma.chartOfAccount.update({ where: { id }, data: body })
  })
}
